background = #1f130b
background-opacity = 0.90
foreground = #efddd3
cursor-color = #fdf5f1
selection-background = #563a28
selection-foreground = #fdf5f1

palette = 0=#1f130b
palette = 1=#e4877b
palette = 2=#9dbe79
palette = 3=#fcb774
palette = 4=#6eb4e1
palette = 5=#d990be
palette = 6=#63cbc7
palette = 7=#efddd3
palette = 8=#856e60
palette = 9=#f1a398
palette = 10=#b6d39a
palette = 11=#fdd6b2
palette = 12=#91c9ef
palette = 13=#e9abd1
palette = 14=#8edfdb
palette = 15=#fdf5f1
