# Cappuccino Night - Hyprlock Colors
$color = rgba(1f130bff)
$inner_color = rgba(1f130bdd)
$outer_color = rgba(e3a072cc)
$font_color = rgba(efddd3ff)
$placeholder_color = rgba(a09087aa)
$check_color = rgba(9dbe79ff)
