foreground            #efddd3
background            #1f130b
background_opacity    0.90
selection_foreground  #fdf5f1
selection_background  #563a28

cursor                #fdf5f1
cursor_text_color     #1f130b

active_border_color   #e3a072
active_tab_background #e3a072

color0 #1f130b
color1 #e4877b
color2 #9dbe79
color3 #fcb774
color4 #6eb4e1
color5 #d990be
color6 #63cbc7
color7 #efddd3
color8 #856e60
color9 #f1a398
color10 #b6d39a
color11 #fdd6b2
color12 #91c9ef
color13 #e9abd1
color14 #8edfdb
color15 #fdf5f1
